source/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('to_do_list_app.urls')),
]

source/to_do_list_app/urls.py
from django.urls import path

from to_do_list_app.views.base import index_view
from to_do_list_app.views.to_dos import add_view, detail_view

urlpatterns = [
    path("", index_view),
    path("todo/add", add_view),
    path("todo/", detail_view)

]

source/to_do_list_app/models.py
from django.db import models


# Create your models here.
class Todo(models.Model):
    STATUS_CHOICES = [
        ('new', 'Новая'),
        ('in_progress', 'В процессе'),
        ('completed', 'Завершено')
    ]

    title = models.CharField(max_length=200, null=False, verbose_name='Заголовок')
    description = models.CharField(max_length=200, null=True, verbose_name='Описание')
    status = models.CharField(max_length=12, choices=STATUS_CHOICES, default='new', verbose_name='Статус')
    date_of_completion = models.DateField(blank=True, null=True, verbose_name='Дата завершения')

    def __str__(self):
        return f'{self.description} - {self.status}'

source/to_do_list_app/views/base.py
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render

from to_do_list_app.models import Todo


def index_view(request: WSGIRequest):
    todos = Todo.objects.all()
    context = {
        'todos': todos
    }
    return render(request, 'index.html', context=context)

source/to_do_list_app/views/to_dos.py
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, redirect

from to_do_list_app.models import Todo


def add_view(request: WSGIRequest):
    if request.method == "GET":
        return render(request, 'add_todo.html')
    print(request.POST)
    todo_data = {
        'title': request.POST.get('title'),
        'description': request.POST.get('description'),
        'status': request.POST.get('status'),
        'date_of_completion': request.POST.get('date_of_completion')
    }
    if todo_data['date_of_completion'] == "":
        todo_data['date_of_completion'] = None
    todo = Todo.objects.create(**todo_data)

    return redirect(f'/todo/?pk={todo.pk}')


def detail_view(request):
    todo_pk = request.GET.get('pk')
    todo = Todo.objects.get(pk=todo_pk)
    context = {'todo': todo}
    return render(request, 'todo.html', context=context)

source/to_do_list_app/templates/add_todo.html
{% load static %}
<!DOCTYPE html>

<html lang="ru-RU" dir="ltr">
<head>
<title>Добавить задачу</title>
<link rel="stylesheet" href="{% static 'styles/css/base.css' %}">
<link rel="stylesheet" href="{% static 'styles/css/dark_mode.css' %}">
<link rel="stylesheet" href="{% static 'styles/css/nav_sidebar.css' %}">
<script src="{% static '/styles/scripts/js/nav_sidebar.js' %}" defer></script>
<link rel="stylesheet" href="{% static 'styles/css/forms.css' %}">









<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" href="/static/admin/css/responsive.css">    
<meta name="robots" content="NONE,NOARCHIVE">
</head>

<body class=" app-to_do_list_app model-todo change-form"
  data-admin-utc-offset="21600">


<div id="container">    
    
    
    <div id="header">
        <div id="branding">        
            <h1 id="site-name">Добавление задач</h1>
        </div>        
        <div id="user-tools">            
                Добро пожаловать            
        </div>        
    </div>
    

    <div class="main" id="main">      
        <div class="content">
            <div id="content" class="colM">          
                <h1>Добавить задачу</h1>          
                <div id="content-main">

                    <form method="post" id="todo_form">
                        {% csrf_token %}
                        <div>
                            <fieldset class="module aligned ">
                
                                <div class="form-row field-title">                        
                                    <div>
                                        <label class="required" for="id_title">Заголовок:</label>   
                                        <input type="text" name="title" class="vTextField" maxlength="200" id="id_title" required>    
                                    </div>
                                </div>

                                <div class="form-row field-description">                        
                                    <div>
                                        <label class="required" for="id_description">Описание:</label>   
                                        <input type="text" name="description" class="vTextField" maxlength="200" required id="id_description">    
                                    </div>            
                                </div>

                                <div class="form-row field-status">            
                                    <div>                    
                                        <label class="required" for="id_status">Статус:</label>
                                        <select name="status" id="id_status">
                                            <option value="new" selected>Новая</option>
                                            <option value="in_progress">В процессе</option>
                                            <option value="completed">Завершено</option>
                                        </select>                                       
                                    </div>            
                                </div>
            
                                <div class="form-row field-date_of_completion">            
                                    <div>                    
                                        <label class="required" for="id_date_of_completion">Дата завершения:</label>
                                        <input type="date" name="date_of_completion" class="vDateField" size="10" id="id_date_of_completion">                    
                                    </div>            
                                </div>    
                            </fieldset>

                            <div class="submit-row">
                                <input type="submit" value="Сохранить" class="default">
                            </div>
                        </div>
                    </form>
                </div>          
                <br class="clear">
            </div>        
            <div id="footer"></div>
        </div>
    </div>
    
</div>
<!-- END Container -->
</body>
</html>

source/to_do_list_app/templates/index.html
cjplfybt{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Задачи</title>
    <link rel="stylesheet" href="{% static 'styles/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'styles/css/dark_mode.css' %}">
    <link rel="stylesheet" href="{% static 'styles/css/nav_sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'styles/css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'styles/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'styles/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    
</head>
<body class="dashboard">
    <div id="container">
        <div id="header">
            
            <div id="branding">        
                <h1 id="site-name"><a href="/">Администрирование задач</a></h1>
            </div>
            <div id="user-tools">            
                Добро пожаловать            
            </div>
        </div> 
        <div id="content-main">

            <div class="app-to_do_list_app module">
                <table class="table-todo">
                    <caption>
                    </caption>        
                    <tr class="model-todo">            
                        <th scope="row">Задачи</th>           
                        <td><a href="/todo/add" class="addlink">Добавить</a></td>                                                                                 
                    </tr>
                    {% for todo in todos %}
                    <tr class="model-todo"> 
                        <th scope="row"><a href="/todo/?pk={{ todo.pk }}">{{ todo.title }}</a> </th>
                        <td><a href="/todo/?pk={{ todo.pk }}" class="changelink">Изменить</a></td>
                    </tr>
                        {% endfor %}
                     
                </table>
            </div>
        </div>
            
    </div>
            
        

        



    
</body>
</html>

source/to_do_list_app/templates/todo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Задачи</title>
    <link rel="stylesheet" href="{% static 'styles/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'styles/css/dark_mode.css' %}">
    <link rel="stylesheet" href="{% static 'styles/css/nav_sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'styles/css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'styles/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'styles/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    
</head>
<body class="dashboard">
    <div id="container">
        <div id="header">            
            <div id="branding">        
                <h1 id="site-name"><a href="/">Администрирование задач</a></h1>
            </div>
            <div id="user-tools">            
                Добро пожаловать            
            </div>
        </div> 

        <div class="breadcrumbs">            
        </div>
                            
            
                <div class="main" id="main">
                  
                    
                      
            
            
            
                                      
                  <div class="content">
                    
                      
                    
                    <!-- Content -->
                    <div id="content" class="colM">
                      
                    
                    <div id="content-main">
                   
              <fieldset class="module aligned ">                            
                <div class="form-row field-description">

                    <table>
                        <caption>
                        </caption>        
                        <tr class="model-todo">            
                            <th scope="row">Заголовок</th>           
                            <td>{{ todo.title }}</td>                                                                                 
                        </tr>
                        <tr class="model-todo">            
                            <th scope="row">Описание</th>           
                            <td>{{ todo.description }}</td>                                                                                 
                        </tr>
                        <tr class="model-todo">            
                            <th scope="row">Статус</th>           
                            <td>{{ todo.status }}</td>                                                                                 
                        </tr>
                        <tr class="model-todo">            
                            <th scope="row">Дата завершения</th>           
                            <td>{{ todo.date_of_completion }}</td>                                                                                 
                        </tr>
                        <th scope="row"><a href="/" aria-current="page">На главную</a></th>                        
                    </table>
                    
                      <br class="clear">
                    </div>
                    <!-- END Content -->
                    <div id="footer"></div>
                  </div>
                </div>
                  
                    
                      

            
                    
                  